### ISSUE TITLE
Get a capture for aead protocols.

### ISSUE THREAD

**Issue by superCodrut** [superCodrut/strongswan#2]
@strainu

**Comment by strainu** [comment]
Wireshark has limited support for AEAD cyphers, added in 2013 by abadea, as described in the following link: https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=8395

I could not extract a working key from our tool, but theoretically the text "ANY 128/192/256-bit cypher" should work

**Comment by superCodrut** [comment]
AEAD cyphers are not suported in wireshark for IPsec IKEv2.

LE. https://ask.wireshark.org/questions/54492/are-aead-cyphers-accepted-for-ikev2-decryption-table
